import * as Images from '../assets'
import {Screen} from '../enums'
import CreditCard from '../screens/creditcard/CreditCard'
import QuickSwap from '../screens/quickswap/QuickSwap'
import {Account, QuickBuySpot, Wallets, Tickers, Home} from './index'

export const TabRoutes = [
  {
    component: Home,
    name: Screen.HomeTab,
    title: 'home',
    activeIcon: Images.HomeActive,
    InactiveIcon: Images.HomeInactive,
    InactiveIconDark: Images.HomeInactiveDark,
    InactiveIconPink: Images.HomePinkGray,
    ActiveIconPink: Images.HomeInctivePink,
    InactiveIconLight: Images.FundingWhite,
  },
  {
    component: Tickers,
    name: Screen.Tickers,
    title: 'tickers',
    activeIcon: Images.TradingActive,
    InactiveIcon: Images.TradingInactive,
    InactiveIconDark: Images.TradingInactiveDark,
    InactiveIconPink: Images.TradingPinkGray,
    ActiveIconPink: Images.TradingInactivePink,
    InactiveIconLight: Images.TradingWhite,
  },
  {
    component: QuickSwap,
    name: Screen.QuickSwap,
    title: 'quick_swap',
    activeIcon: Images.FundingActive,
    InactiveIcon: Images.FundingInactive,
    InactiveIconDark: Images.FundingInactiveDark,
    InactiveIconPink: Images.FundingPinkGray,
    ActiveIconPink: Images.FundingInctivePink,
    InactiveIconLight: Images.FundingWhite,
  },
  // {
  //   component: Gbex,
  //   name: Screen.GbexScreen,
  //   title: 'gbex',
  //   activeIcon: Images.GbexActive,
  //   InactiveIcon: Images.GbexInactive,
  //   InactiveIconDark: Images.GbexInactiveDark,
  //   InactiveIconPink: Images.GbexPinkGray,
  //   ActiveIconPink: Images.GbexInctivePink,
  //   InactiveIconLight: Images.GbexWhite,
  // },
  {
    component: Wallets,
    name: Screen.Wallets,
    title: 'wallet',
    activeIcon: Images.WalletActive,
    InactiveIcon: Images.WalletInactive,
    InactiveIconDark: Images.WalletInactiveDark,
    ActiveIconPink: Images.WalletInctivePink,
    InactiveIconPink: Images.WalletPinkGray,
    InactiveIconLight: Images.WalletWhite,
  },
  {
    component: Account,
    name: Screen.Account,
    title: 'more',
    activeIcon: Images.MoreActive,
    InactiveIcon: Images.MoreInactive,
    InactiveIconDark: Images.MoreInactiveDark,
    ActiveIconPink: Images.MoreInctivePink,
    InactiveIconPink: Images.MorePinkGray,
    InactiveIconLight: Images.MoreWhite,
  },
]

export const TabRoutesReverse = [
  {
    component: Account,
    name: Screen.Account,
    title: 'more',
    activeIcon: Images.MoreActive,
    InactiveIcon: Images.MoreInactive,
    InactiveIconDark: Images.MoreInactiveDark,
    ActiveIconPink: Images.MoreInctivePink,
    InactiveIconPink: Images.MorePinkGray,
    InactiveIconLight: Images.MoreWhite,
  },
  {
    component: Wallets,
    name: Screen.Wallets,
    title: 'wallet',
    activeIcon: Images.WalletActive,
    InactiveIcon: Images.WalletInactive,
    InactiveIconDark: Images.WalletInactiveDark,
    ActiveIconPink: Images.WalletInctivePink,
    InactiveIconPink: Images.WalletPinkGray,
    InactiveIconLight: Images.WalletWhite,
  },
  // {
  //   component: Gbex,
  //   name: Screen.GbexScreen,
  //   title: 'gbex',
  //   activeIcon: Images.GbexActive,
  //   InactiveIcon: Images.GbexInactive,
  //   InactiveIconDark: Images.GbexInactiveDark,
  //   InactiveIconPink: Images.GbexPinkGray,
  //   ActiveIconPink: Images.GbexInctivePink,
  //   InactiveIconLight: Images.GbexWhite,
  // },
  {
    component: QuickSwap,
    name: Screen.QuickSwap,
    title: 'quick_swap',
    activeIcon: Images.FundingActive,
    InactiveIcon: Images.FundingInactive,
    InactiveIconDark: Images.FundingInactiveDark,
    InactiveIconPink: Images.FundingPinkGray,
    ActiveIconPink: Images.FundingInctivePink,
    InactiveIconLight: Images.FundingWhite,
  },
  {
    component: Tickers,
    name: Screen.Tickers,
    title: 'tickers',
    activeIcon: Images.TradingActive,
    InactiveIcon: Images.TradingInactive,
    InactiveIconDark: Images.TradingInactiveDark,
    InactiveIconPink: Images.TradingPinkGray,
    ActiveIconPink: Images.TradingInactivePink,
    InactiveIconLight: Images.TradingWhite,
  },
  {
    component: Home,
    name: Screen.HomeTab,
    title: 'home',
    activeIcon: Images.HomeActive,
    InactiveIcon: Images.HomeInactive,
    InactiveIconDark: Images.HomeInactiveDark,
    InactiveIconPink: Images.HomePinkGray,
    ActiveIconPink: Images.HomeInctivePink,
    InactiveIconLight: Images.FundingWhite,
  },
]
