export const UPDATE_CONNECTIVITY_STATUS = 'UPDATE_CONNECTIVITY_STATUS';
export const LOGIN_ACTIVITY_LOADER = 'LOGIN_ACTIVITY_LOADER';
export const LOGIN = 'LOGIN';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_DATA = 'LOGIN_DATA';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';

export const LOGOUT = 'LOGOUT';

export const UPDATE_USERDATA = 'UPDATE_USERDATA';
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_INDUSTRIES = 'GET_INDUSTRIES';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_KYC_DATA = 'GET_KYC_DATA';
export const LOADING_DATA = 'LOADING_DATA';
export const SUBMIT_KYC_DATA = 'SUBMIT_KYC_DATA';

export const GET_FUND_BALANCE = 'GET_FUND_BALANCE';
export const GET_PAIR_DETAILS = 'GET_PAIR_DETAILS';
export const QUICK_BUY = 'QUICK_BUY';
export const QUICK_BUY_SPOT_HISTORY = 'QUICK_BUY_SPOT_HISTORY';
export const QUICK_BUY_TRADE_HISTORY = 'QUICK_BUY_TRADE_HISTORY';

export const GET_BALANCE_DEPOSIT_HISTORY = 'GET_BALANCE_DEPOSIT_HISTORY';
export const GET_BALANCE_WITHDRAWAL_HISTORY = 'GET_BALANCE_WITHDRAWAL_HISTORY';
export const UPDATE_TICKERS = 'UPDATE_TICKERS';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const GET_WALLET_LIST = 'GET_WALLET_LIST';

export const UPDATE_APP_APPROACH = 'UPDATE_APP_APPROACH';
export const UPDATE_CUSTOM_ALERT = 'UPDATE_CUSTOM_ALERT';

export const UPDATE_PASSCODE_STATUS = 'UPDATE_PASSCODE_STATUS';
export const SET_BIOMETRIC_TYPE = 'SET_BIOMETRIC_TYPE';
export const SET_BIOMETRY = 'SET_BIOMETRY';

export const GET_STATISTICS = 'GET_STATISTICS';
export const UPDATE_THEME = 'UPDATE_THEME';
export const UPDATE_COLOR = 'UPDATE_COLOR';
export const UPDATE_REGION = 'UPDATE_REGION';

export const HIDE_SMALL_BALANCES = 'HIDE_SMALL_BALANCES';

export const BUY_GBEX = 'BUY_GBEX';
export const GBEX_HISTORY = 'GBEX_HISTORY';
export const GET_LIVE_PRICE = 'GET_LIVE_PRICE';
export const UPDATE_BALANCE_VISIBILITY = 'UPDATE_BALANCE_VISIBILITY';

export const ADD_BENEFICIARY = 'ADD_BENEFICIARY';
export const GET_USER_BENEFICIARY = 'GET_USER_BENEFICIARY';
export const CREATE_INTERNAL_PAYMENTS = 'CREATE_INTERNAL_PAYMENTS';
export const GET_INTERNAL_PAYMENTS = 'GET_INTERNAL_PAYMENTS';
export const CANCEL_INTERNAL_PAYMENT = 'CANCEL_INTERNAL_PAYMENT';
export const DOWNLOAD_DEPOSIT_PAYMENT = 'DOWNLOAD_DEPOSIT_PAYMENT';
export const GET_USER_INFORMATION = 'GET_USER_INFORMATION';
export const GET_BANKS = 'GET_BANKS';
export const MAKE_CREDIT_CARD_PAYMENT = 'MAKE_CREDIT_CARD_PAYMENT';
export const GET_CREDIT_CARD_PAYMENTS = 'GET_CREDIT_CARD_PAYMENTS';

export const GET_CURRENCY_STATUS = 'GET_CURRENCY_STATUS';
export const GET_DEPOSIT_LISTING = 'GET_DEPOSIT_LISTING';
export const GET_WITHDRAWAL_LISTING = 'GET_WITHDRAWAL_LISTING';
export const CREATE_WITHDRAWAL_REQUEST = 'CREATE_WITHDRAWAL_REQUEST';
export const CREATE_DEPOSIT_REQUEST = 'CREATE_DEPOSIT_REQUEST';
export const CANCEL_DEPOSIT_REQUEST = 'CANCEL_DEPOSIT_REQUEST';
export const CANCEL_WITHDRAWAL_REQUEST = 'CANCEL_WITHDRAWAL_REQUEST';
export const DOWNLOAD_WITHDRAWAL_PAYMENT = 'DOWNLOAD_WITHDRAWAL_PAYMENT';
export const GET_ASSET_METADATA = 'GET_ASSET_METADATA';
export const GET_ANNOUNCEMENTS = 'GET_ANNOUNCEMENTS';

export const UPDATE_FAVOURITE = 'UPDATE_FAVOURITE';

export const GET_KYB_DATA = 'GET_KYB_DATA';
export const SUBMIT_KYB_DATA = 'SUBMIT_KYB_DATA';
export const ADD_KYB_DATA = 'ADD_KYB_DATA';

export const UPDATE_MAIN_CURRENCY = 'UPDATE_MAIN_CURRENCY';
export const UPDATE_SECONDARY_CURRENCY = 'UPDATE_SECONDARY_CURRENCY';
export const GET_PAIRS = 'GET_PAIRS';
export const PAIRS_ERROR = 'PAIRS_ERROR';
export const PAIRS_LOADING = 'PAIRS-LOADING';
export const UPDATE_FAVOURITE_SPOT = 'UPDATE_FAVOURITE_SPOT';
export const GET_GBEX_STATUS = 'GET_GBEX_STATUS';
export const GET_GBEX_REWARDS = 'GET_GBEX_REWARDS';
export const REDEEM_REWARDS = 'REDEEM_REWARDS';
export const GET_DRIP_LOGS = 'GET_DRIP_LOGS';
export const GET_REWARDS_HISTORY = 'GET_REWARDS_HISTORY';

export const GET_STABLE_COIN = 'GET_STABLE_COIN';

export const GET_TICKERS_LOADING = 'GET_TICKERS_LOADING';
export const GET_TICKERS_SUCCESSFULL = 'GET_TICKERS_SUCCESSFULL';
export const GET_TICKERS_ERROR = 'GET_TICKERS_ERROR';

export const GET_MIN_DEPOSIT_LOADING = 'GET_MIN_DEPOSIT_LOADING';
export const GET_MIN_DEPOSIT_SUCCESSFULL = 'GET_MIN_DEPOSIT_SUCCESSFULL';
export const GET_MIN_DEPOSIT_ERROR = 'GET_MIN_DEPOSIT_ERROR';

export const GET_CURRENT_STAKED_START = 'GET_CURRENT_STAKED_START';
export const GET_CURRENT_STAKED_SUCCESS = 'GET_CURRENT_STAKED_SUCCESS';
export const GET_CURRENT_STAKED_END = 'GET_CURRENT_STAKED_END';

export const GET_CURRENT_EARNINGS_START = 'GET_CURRENT_EARNINGS_START';
export const GET_CURRENT_EARNINGS_SUCCESS = 'GET_CURRENT_EARNINGS_SUCCESS';
export const GET_CURRENT_EARNINGS_END = 'GET_CURRENT_EARNINGS_END';

export const UPDATE_STAKE_STATE = 'UPDATE_STAKE_STATE';
export const GET_ALLOWED_REGION = 'GET_ALLOWED_REGION';
export const UPDATE_SERVER_REACHABILITY = 'UPDATE_SERVER_REACHABILITY';

export const GET_MARKET_LIST = 'GET_MARKET_LIST';
export const GET_LAUNCHPAD_LIST = 'GET_LAUNCHPAD_LIST';
export const GET_LAUNCHPAD_SETTING = 'GET_LAUNCHPAD_SETTING';
export const GET_LAUNCHPAD_HISTORY = 'GET_LAUNCHPAD_HISTORY';

export const KYB_DATA = 'KYB_DATA';
export const RESET_INITIAL = 'RESET_INITIAL';
export const STAKE_DATA = 'STAKE_DATA';
export const STAKE_HISTROY_DATA = 'STAKE_HISTROY_DATA';

export const GET_IBANS_TYPE_DATA = 'GET_IBANS_TYPE_DATA';
export const GET_IBANS_ACTIVE_DATA = 'GET_IBANS_ACTIVE_DATA';
export const GET_IBANS_REQUEST_DATA = 'GET_IBANS_REQUEST_DATA';
export const GET_IBANS_TRANSACTIONS = 'GET_IBANS_TRANSACTIONS';

export const GET_NEW_CARDS_LIST = 'GET_NEW_CARDS_LIST';
export const GET_DELIVERY_LIST = 'GET_DELIVERY_LIST';
export const GET_ACTIVE_CARD_LIST = 'GET_ACTIVE_CARD_LIST';
export const GET_CARD_REQUESTED_LIST = 'GET_CARD_REQUESTED_LIST';
export const GET_CARD_TRANSACTIONS_LIST = 'GET_CARD_TRANSACTIONS_LIST';
export const CARD_TYPE_REQUEST_DATA = 'CARD_TYPE_REQUEST_DATA';
export const RESET_CARD_TYPE_REQUEST_DATA = 'RESET_CARD_TYPE_REQUEST_DATA';
